# Generated by Django 5.2 on 2025-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_title',
            field=models.CharField(default='Thread', max_length=200),
            preserve_default=False,
        ),
    ]
