# Generated by Django 6.0 on 2025-12-05 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_author_alter_thread_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_resolved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='resolved_suggesters',
            field=models.ManyToManyField(related_name='user_suggests_resolve_for_thread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='watchers',
            field=models.ManyToManyField(related_name='user_watches_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
