# Generated by Django 6.0 on 2025-12-08 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_thread_is_resolved_thread_resolved_suggesters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='chat.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='resolved_suggesters',
            field=models.ManyToManyField(blank=True, related_name='user_suggests_resolve_for_thread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='user_watches_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
