# Generated by Django 6.0 on 2025-12-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_thread_id_alter_thread_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
